### ISSUE TITLE
Missing consumptions values

### ISSUE THREAD

**Issue by novicell-jhj** [OlivierZal/com.melcloud#64] opened 2022-12-07 12:18 UTC
Hey Olivier,
Something happened the other day.
Suddenly I'm missing all the consumptions values. 
I have not changed any settings for several months, but can see the version bumps up very frequently.

![Messenger_and_Homey_Pro](https://user-images.githubusercontent.com/113981570/206177532-7f76e0d6-b28f-4642-93c7-605f53b1a125.jpg)

**Comment by novicell-jhj** [comment] 2022-12-08 09:18
It was fixed when save the settings again.

**Comment by OlivierZal** [comment] 2022-12-10 20:38
Hi @novicell-jhj,

Sorry, I didn't receive a notification for your issue. 

I'm glad you have it solved in the meanwhile. 

Last updates are rather module upgrades, code readability and minor changes. 

However I've changed something related to energy reporting: now I use the user local time and not UTC (defaulted by Homey). It should have been seamless but maybe some overlap happened in some cases (it didn't happen to me). 

Kind regards

**Comment by novicell-jhj** [comment] 2022-12-12 09:14
Hey Olivier
There are some fishy on this issue.
Every morning, when I open Homey, the values are not updated. But when I restart the MelCloud App, then it updates.
So the value are there, but are not updated in your app often enough.

**Comment by MTRKhn** [comment] 2022-12-12 09:17
What is your device update frequency ? Anything below 5 minutes might trigger throttling on the MelCloud API side.

**Comment by MTRKhn** [comment] 2022-12-12 16:46
It happened from time to time that i have no update for an hour or so and if i restart the app on Homey, data are properly gathered. Especially since they screwed up their backend API two weeks ago. Now i have a flow that restart your app 30 minutes and all good :-P

**Comment by OlivierZal** [comment] 2022-12-12 17:06
Ok so it might be a issue related to MELCloud API and not the Homey app.

**Comment by OlivierZal** [comment] 2022-12-12 17:56
Oh, maybe it's code-related after all.

**Comment by OlivierZal** [comment] 2022-12-13 09:21
@novicell-jhj, @MTRKhn, fixed with the newest test version.

Issue was that sometimes `forEach` is not fast enough to aggregate data, so I replaced by a `for..of` loop: https://github.com/OlivierZal/com.melcloud/commit/9bae16d8f0f067a6e220110e8dce8dcd0244f503

**Comment by OlivierZal** [comment] 2022-12-14 10:43
Hi @novicell-jhj, did last test version solved your issue?

I still notice on some users that MELCloud energy reporting API sends value `0` for every category, what is not normal...

**Comment by OlivierZal** [comment] 2022-12-16 14:17
Hi @novicell-jhj / @janhjordie, do you still encounter the reporting issue?

**Comment by OlivierZal** [comment] 2022-12-17 00:55
@novicell-jhj / @janhjordie @MTRKhn 

I think my last comment is (one of) the root cause: on the 2 heat pumps associated to my account: at 00:00 one has been updated and the other not, at 1:00 the second one has been updated. 

So I'll try to run reporting at 00:05 in the next version, let's see if then all the devices are updated. 

I keep the issue open in the meanwhile.

**Comment by OlivierZal** [comment] 2022-12-17 01:02
Note: this issue is new because previously the reporting was run according to default Homey time zone, that is UTC, at 1:00 (Winter) or 2:00 (Summer).

**Comment by janhjordie** [comment] 2022-12-17 12:41
Hey Olivier
Just looked at your app, and now it's 13.40 and the values are not updated yet. 
But if I restart the app, then the values appear

**Comment by OlivierZal** [comment] 2022-12-17 13:45
Hi @janhjordie, I haven't updated the app yet. I'll publish a fix by midnight. 

I'll try with 00:01 and we'll see tomorrow if it worked. If not, I'll try 00:05 in a next version.

Anyway now I'm pretty sure that's the root cause: it's just the matter of a difference of some (milli)seconds between Homey and MELCloud times.

**Comment by OlivierZal** [comment] 2022-12-17 16:42
@janhjordie, the fix is ready: https://github.com/OlivierZal/com.melcloud/commit/ae13658fbcac90376c7e65dc82d1bc8ba72e22a5

However I didn’t test enough locally to deploy it in a test version, will do so tomorrow…

**Comment by OlivierZal** [comment] 2022-12-18 23:56
@janhjordie, @MTRKhn ,

I've just released a test version right now, so unfortunately you'll be able to verify only tomorrow that fix has worked.

Success confirmation will rely on your feedback since I've no more device with a working reporting associated to my account.

**Comment by OlivierZal** [comment] 2022-12-19 14:17
@janhjordie, @MTRKhn, in addition to potentiel timezone issues and API bugs, I found the real culprit: https://github.com/OlivierZal/com.melcloud/commit/e58670223b87a59b189e4eb6f3cb081faf19768b#diff-45823121a4961197e74e9694690f25f9175071624964b625678aeb7eaef7563aR213

**Comment by OlivierZal** [comment] 2022-12-20 05:35
Hi @janhjordie, did it work?

**Comment by OlivierZal** [comment] 2022-12-21 07:56
@janhjordie, according to fake tests I’ve made, the issue seems to be solved, do you confirm?

**Comment by OlivierZal** [comment] 2022-12-23 14:04
@janhjordie, @novicell-jhj, can I close the issue or do you still encounter one with the latest app version?

**Comment by janhjordie** [comment] 2022-12-23 14:06
This is just captured from 8.0.6. 
So it still seems to have an issue

![image](https://user-images.githubusercontent.com/79910/209348746-95793604-123c-4c95-828a-7d9be806b446.png)

**Comment by OlivierZal** [comment] 2022-12-23 14:07
😭

**Comment by OlivierZal** [comment] 2022-12-23 14:12
@janhjordie, which time zone do you read on this page?

https://tools.developer.homey.app/tools/system

**Comment by janhjordie** [comment] 2022-12-23 14:14
timezone	"Europe/Copenhagen"

**Comment by janhjordie** [comment] 2022-12-23 14:22
Maybe just try fetch the values every hour if not set. 
I fetch data from the heat pump every 3 minutes

**Comment by OlivierZal** [comment] 2022-12-23 14:22
@janhjordie, would you mind provide me again an access to your device so I can see which values your report API returns around 00:00 AM CET? I want the app work best for you and I'm not the kind of guy to give up...

Before the issue occurred for you, the report was run every day at 00:00 AM UTC (01:00 / 02:00 AM CET / CEST). Issue does not happen for my air-to-air devices, whose metrics can be refreshed hourly by the way (contrary to air-to-water heat pumps).

**Comment by janhjordie** [comment] 2022-12-23 14:24
You have access now 🤘

**Comment by OlivierZal** [comment] 2022-12-23 14:25
> Maybe just try fetch the values every hour if not set. 
> I fetch data from the heat pump every 3 minutes

I could but the last app updates aimed to limit queries both to avoid MELCloud issues and to relieve Homey from frequent / heavy loads.

**Comment by janhjordie** [comment] 2022-12-23 14:28
Yeah,that's why I only poll every 3 minutes.

**Comment by OlivierZal** [comment] 2022-12-23 23:11
So @janhjordie, @MTRKhn, now I proved that the real culprit is the one I suspected from the beginning: MELCloud API refreshes its values only after 00:05:00 AM CET.

At 02:50 AM
<img width="567" alt="2022-12-24 00 02 50" src="https://user-images.githubusercontent.com/88216225/209412451-fde19a13-6874-4ef4-8e63-29db6e16c566.png">

At 00:05 AM
<img width="601" alt="2022-12-24 00 05 24" src="https://user-images.githubusercontent.com/88216225/209412477-4f72db16-e068-48e4-aa07-ed3b605205c4.png">

So I'll make the report run every 00:10 AM, it should solve the issue definitively.

**Comment by OlivierZal** [comment] 2022-12-23 23:51
https://github.com/OlivierZal/com.melcloud/commit/30caa992a49edc179594c2a5e9f686ebac5a5cfc, already in production.

**Closed by OlivierZal** 2022-12-23 23:51 UTC

**Comment by OlivierZal** [comment] 2022-12-26 11:42
Hi @janhjordie, first of all merry Christmas! Do you confirm the resolution? Otherwise I'll make additional tests...

When I checked yesterday morning,  new values were retrieved at the right time (00:10 AM GMT+1) with values "0" but there were the values retrieved from the MELCloud report API.

**Comment by OlivierZal** [comment] 2022-12-28 21:26
Hi @janhjordie, nearly 1 week after the update, do you confirm the resolution?

**Comment by janhjordie** [comment] 2022-12-28 21:34
Sorry for the late feedback. Everything is working again. 
Thanks Olivier 🙏🐿️😍

**Comment by OlivierZal** [comment] 2022-12-28 21:35
Super! 🤟

**Comment by OlivierZal** [comment] 2023-01-07 13:29
Hi @MTRKhn and @janhjordie,

I invite to check latest 9.1.0 test version's (new) app settings! (I said it right: not device settings but **app** settings).

**Comment by janhjordie** [comment] 2023-01-07 13:34
Looks pretty sweet 😃

![image](https://user-images.githubusercontent.com/79910/211153386-c8780271-4082-4969-abf0-7a617ab81d34.png)

**Comment by OlivierZal** [comment] 2023-02-14 09:04
Hi @MTRKhn and @janhjordie, I have a user who has an issue with some dashboard values which are not updated (only outdoor temperature and wifi strength are).

When I investigated I saw that the values are well retrieved by Homey but are stuck on the MELCloud API and also the official MELCloud app.

Do you encounter the same issue on your side?

**Comment by OlivierZal** [comment] 2023-02-20 22:07
@MTRKhn, @janhjordie, FYI it seems to be back to normal since today.
