### ISSUE TITLE
Device Unavailable

### ISSUE THREAD

**Issue by jlgnav** [OlivierZal/com.melcloud#344] opened 2024-02-20 16:04 UTC
After the last update, I am not able to connect to the heatpump

Message:

Device Unavailable
horizontal InvalidTypeError: undefined is undefined but expected string (invalid_type)

**Comment by OlivierZal** [comment] 2024-02-21 00:37
Hi @jlgnav, upcoming release will fix your issue. 
You can download it in its test version: https://homey.app/en-us/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment] 2024-02-21 00:42
Hi @icaros1, you can download the test version too, but your message seems to be different: I don’t see how you could get a target temperature at 0.

Can you please contact me via https://slack.athom.com/ ?
I will to reproduce and investigate what happens.

**Comment by OlivierZal** [comment] 2024-02-21 16:38
Hi @Nfs2233, can you please discuss with me in https://slack.athom.com/ ? I'll investigate.

**Comment by OlivierZal** [comment] 2024-02-21 23:39
@Nfs2233, @icaros1, should be fixed in this new version: https://homey.app/a/com.mecloud

**Closed by OlivierZal** 2024-02-21 23:39 UTC
